Repository inclusive-design/idg-design-system, pull requests merged in 2023-07, with the labels that each got.

#2 chore: add commit message linting; add CSS, JS, and Markdown linting
  .eslintrc.js
  .github/dependabot.yml
  .github/workflows/lint.yml
  .husky/commit-msg
  .husky/pre-commit
  .markdownlint-cli2.cjs
  .stylelintrc.js
  commitlint.config.js
  eleventy.config.js
  package-lock.json
  package.json
  src/_data/components.js
  src/_includes/components/link/link.config.js
  src/index.md
  src/static/css/link.css
  src/static/css/reset.css
  src/static/design-system/css/design-system.css
Labels: enhancement

#5 chore: add Release Please configuration (resolve #4)
  .github/workflows/release.yml
Labels: enhancement

#6 feat: add build script for CSS export (resolve #3)
  .gitignore
  .husky/pre-commit
  .npmignore
  .stylelintrc.js
  README.md
  bin/check-imports.js
  package-lock.json
  package.json
  src/static/css/main.css
Labels: enhancement

#1 feat: colors and fonts
  src/_includes/components/color/color.config.js
  src/_includes/components/color/color.njk
  src/_includes/layout.njk
  src/static/css/color.css
  src/static/css/main.css
  src/static/css/utilities.css
  src/static/css/variables.css
Labels: enhancement

#9 feat: adjust colours with updates from Figma
  src/_includes/components/color/color.config.js
  src/_includes/components/color/color.njk
  src/components-full-pages.njk
  src/components-pages.njk
  src/static/css/color.css
  src/static/css/reset.css
  src/static/css/variables.css
Labels: bug, enhancement

#20 feat: add badge component (resolves #11)
  src/_includes/components/badge/badge.config.js
  src/_includes/components/badge/badge.njk
  src/_includes/layout.njk
  src/static/css/badge.css
  src/static/css/main.css
  src/static/css/variables.css
Labels: enhancement

#21 fix: missing space variables
  src/static/css/variables.css
Labels: bug

#19 feat: add typestack component (resolves #16)
  src/_includes/components/typography/typography.config.js
  src/_includes/components/typography/typography.njk
  src/_includes/layout.njk
  src/static/css/font.css
  src/static/css/link.css
  src/static/css/main.css
  src/static/css/typography.css
  src/static/css/utilities.css
  src/static/css/variables.css
  src/static/fonts/martel-sans-v12-latin-700.woff2
  src/static/fonts/martel-sans-v12-latin-800.woff2
  src/static/fonts/martel-sans-v12-latin-regular.woff2
  src/static/fonts/martel-v10-latin-700.woff2
  src/static/fonts/martel-v10-latin-800.woff2
  src/static/fonts/martel-v10-latin-regular.woff2
Labels: enhancement

#23 feat: add flow and prose utilities, use logical properties
  .stylelintrc.js
  eleventy.config.js
  package-lock.json
  package.json
  src/_includes/components/badge/README.md
  src/_includes/components/color/README.md
  src/_includes/components/flow/README.md
  src/_includes/components/flow/flow.config.js
  src/_includes/components/flow/flow.njk
  src/_includes/components/link/README.md
  src/_includes/components/typography/README.md
  src/_includes/components/typography/typography.njk
  src/components-pages.njk
  src/static/css/badge.css
  src/static/css/reset.css
  src/static/css/utilities.css
Labels: enhancement

#24 feat: add new 90px space
  src/_includes/components/color/color.njk
  src/static/css/utilities.css
  src/static/css/variables.css
Labels: enhancement

#22 feat: add link component (resolves #12)
  src/_includes/components/color/color.config.js
  src/_includes/components/link/link.config.js
  src/_includes/components/link/link.njk
  src/_includes/layout.njk
  src/static/css/color.css
  src/static/css/link.css
  src/static/css/main.css
  src/static/css/utilities.css
  src/static/css/variables.css
Labels: enhancement

#28 feat: card components (resolves #15)
  src/_includes/components/card/README.md
  src/_includes/components/card/card.config.js
  src/_includes/components/card/card.njk
  src/_includes/components/cards/README.md
  src/_includes/components/cards/cards.config.js
  src/_includes/components/cards/cards.njk
  src/_includes/components/color/color.njk
  src/_includes/components/typography/typography.config.js
  src/_includes/design-system/library.njk
  src/_includes/design-system/page.njk
  src/_includes/layout.njk
  src/components-full-pages.njk
  src/static/css/_badge.css
  src/static/css/_card.css
  src/static/css/_cards.css
  src/static/css/_typography.css
  src/static/css/_variables.css
  src/static/css/main.css
  src/static/design-system/css/design-system.css
  src/static/design-system/css/reset.css
  src/static/svg/arrow.svg
Labels: enhancement

#31 feat: add horizontal rule component (resolves #26)
  src/_includes/components/horizontal-rule/README.md
  src/_includes/components/horizontal-rule/horizontal-rule.config.js
  src/_includes/components/horizontal-rule/horizontal-rule.njk
  src/static/css/_horizontal-rule.css
  src/static/css/main.css
Labels: enhancement

#29 feat: pagination link component (resolves #10)
  src/_includes/components/pagination/README.md
  src/_includes/components/pagination/pagination.config.js
  src/_includes/components/pagination/pagination.njk
  src/static/css/_pagination.css
  src/static/css/main.css
Labels: enhancement

#30 feat: navigation (resolves #14)
  src/_includes/components/color/color.config.js
  src/_includes/components/navigation/README.md
  src/_includes/components/navigation/navigation.config.js
  src/_includes/components/navigation/navigation.njk
  src/static/css/_color.css
  src/static/css/_font.css
  src/static/css/_link.css
  src/static/css/_navigation.css
  src/static/css/_utilities.css
  src/static/css/_variables.css
  src/static/css/main.css
  src/static/fonts/mulish-v12-latin-500.woff2
  src/static/fonts/mulish-v12-latin-700.woff2
  src/static/svg/close.svg
  src/static/svg/idrc.svg
  src/static/svg/menu.svg
Labels: enhancement

#32 fix: desktop navigation padding
  src/static/css/_navigation.css
Labels: bug

#39 fix: issues with different states (resolves #33)
  src/static/css/_card.css
Labels: bug

#40 fix: text color for body (resolves #34)
  src/static/design-system/css/reset.css
Labels: bug

#41 fix: adjust type scale for mobile devices (resolves #37)
  src/static/css/_variables.css
Labels: bug

#42 fix: pagination (resolves #35, resolves #36)
  src/static/css/_pagination.css
Labels: bug

#38 feat: implement calls to action component (resolve #27)
  src/_includes/components/call-to-action/README.md
  src/_includes/components/call-to-action/call-to-action.config.js
  src/_includes/components/call-to-action/call-to-action.njk
  src/static/css/_call-to-action.css
  src/static/css/main.css
Labels: enhancement
